/*
 * Automatically generated by /data/sean.yang_sophgo/ten/sophpi-huashan/product-sample/access-guard-turnkey/tools/gen_autoconf_h. Please don't edit.  */

#ifndef __AUTO_CONFIGURATION_H__
#define __AUTO_CONFIGURATION_H__


#define CONFIG_CUSTOMER 	  "cvitek"
#define CONFIG_CVI_SOC_CR182X 	 1
#define CONFIG_APP_MUSL 	 1
#define CONFIG_MW_SDK_VER_MUSL 	 1
#define CONFIG_ENABLE_GUI_LVGL 	 1
#define CONFIG_ALGORITHM_VENDOR_AISDK 	 1
#define CONFIG_ALGORITHM_VENDOR 	  "aisdk"
#define CONFIG_DUAL_SENSOR_SUPPORT 	 1
#define CONFIG_SENSOR0_IS_RGB 	 1
#define CONFIG_ENABLE_ISPD 	 1
#define CONFIG_INPUT_TP 	 1
#define CONFIG_BUILD_APP_LEGACY 	 1
#define CONFIG_VI_ROTATION_90 	 1
#define CONFIG_VO_ROTATION_NONE 	 1
#define CONFIG_RGB_VIDEO_RTSP_SUPPORT 	 1
#define CONFIG_RGB_VIDEO_RTSP_VENC_BIND_VPSS 	 1
#define CONFIG_IR_VIDEO_RTSP_SUPPORT 	 1
#define CONFIG_IR_VIDEO_RTSP_VENC_BIND_VPSS 	 1
#define CONFIG_FACTORY_TEST_SUPPORT 	 1
#define CONFIG_USE_DEFAULT_PQ_PARAM 	 1
#define CONFIG_PANEL_DISPLAY_SUPPORT 	 1
#define CONFIG_PANEL_DISPLAY_HOR 	  720
#define CONFIG_PANEL_DISPLAY_VER 	  1280
#define CONFIG_AUDIO_SUPPORT 	 1
#define CONFIG_BOOTLOGO_SUPPORT 	 1
#define CONFIG_DATABASE 	 1
#define CONFIG_NFC_SUPPORT 	 1

#endif

