#ifndef __CVI_HAL_GPIO_H__
#define __CVI_HAL_GPIO_H__
#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */
typedef void (*FunType)();

typedef enum _CVI_HAL_GPIO_NUM_E {
	CVI_HAL_HALGPIOA_00 = 480,
	CVI_HAL_GPIOA_01,   CVI_HAL_GPIOA_02,   CVI_HAL_GPIOA_03,   CVI_HAL_GPIOA_04,   CVI_HAL_GPIOA_05,
	CVI_HAL_GPIOA_06,   CVI_HAL_GPIOA_07,   CVI_HAL_GPIOA_08,   CVI_HAL_GPIOA_09,   CVI_HAL_GPIOA_10,
	CVI_HAL_GPIOA_11,   CVI_HAL_GPIOA_12,   CVI_HAL_GPIOA_13,   CVI_HAL_GPIOA_14,   CVI_HAL_GPIOA_15,
	CVI_HAL_GPIOA_16,   CVI_HAL_GPIOA_17,   CVI_HAL_GPIOA_18,   CVI_HAL_GPIOA_19,   CVI_HAL_GPIOA_20,
	CVI_HAL_GPIOA_21,   CVI_HAL_GPIOA_22,   CVI_HAL_GPIOA_23,   CVI_HAL_GPIOA_24,   CVI_HAL_GPIOA_25,
	CVI_HAL_GPIOA_26,   CVI_HAL_GPIOA_27,   CVI_HAL_GPIOA_28,   CVI_HAL_GPIOA_29,   CVI_HAL_GPIOA_30,
	CVI_HAL_GPIOA_31,

	CVI_HAL_GPIOB_00 = 448,
	CVI_HAL_GPIOB_01,   CVI_HAL_GPIOB_02,   CVI_HAL_GPIOB_03,   CVI_HAL_GPIOB_04,   CVI_HAL_GPIOB_05,
	CVI_HAL_GPIOB_06,   CVI_HAL_GPIOB_07,   CVI_HAL_GPIOB_08,   CVI_HAL_GPIOB_09,   CVI_HAL_GPIOB_10,
	CVI_HAL_GPIOB_11,   CVI_HAL_GPIOB_12,   CVI_HAL_GPIOB_13,   CVI_HAL_GPIOB_14,   CVI_HAL_GPIOB_15,
	CVI_HAL_GPIOB_16,   CVI_HAL_GPIOB_17,   CVI_HAL_GPIOB_18,   CVI_HAL_GPIOB_19,   CVI_HAL_GPIOB_20,
	CVI_HAL_GPIOB_21,   CVI_HAL_GPIOB_22,   CVI_HAL_GPIOB_23,   CVI_HAL_GPIOB_24,   CVI_HAL_GPIOB_25,
	CVI_HAL_GPIOB_26,   CVI_HAL_GPIOB_27,   CVI_HAL_GPIOB_28,   CVI_HAL_GPIOB_29,   CVI_HAL_GPIOB_30,
	CVI_HAL_GPIOB_31,

	CVI_HAL_GPIOC_00 = 416,
	CVI_HAL_GPIOC_01,   CVI_HAL_GPIOC_02,   CVI_HAL_GPIOC_03,   CVI_HAL_GPIOC_04,   CVI_HAL_GPIOC_05,
	CVI_HAL_GPIOC_06,   CVI_HAL_GPIOC_07,   CVI_HAL_GPIOC_08,   CVI_HAL_GPIOC_09,   CVI_HAL_GPIOC_10,
	CVI_HAL_GPIOC_11,   CVI_HAL_GPIOC_12,   CVI_HAL_GPIOC_13,   CVI_HAL_GPIOC_14,   CVI_HAL_GPIOC_15,
	CVI_HAL_GPIOC_16,   CVI_HAL_GPIOC_17,   CVI_HAL_GPIOC_18,   CVI_HAL_GPIOC_19,   CVI_HAL_GPIOC_20,
	CVI_HAL_GPIOC_21,   CVI_HAL_GPIOC_22,   CVI_HAL_GPIOC_23,   CVI_HAL_GPIOC_24,   CVI_HAL_GPIOC_25,
	CVI_HAL_GPIOC_26,   CVI_HAL_GPIOC_27,   CVI_HAL_GPIOC_28,   CVI_HAL_GPIOC_29,   CVI_HAL_GPIOC_30,
	CVI_HAL_GPIOC_31,

	CVI_HAL_GPIOD_00 = 404,
	CVI_HAL_GPIOD_01,   CVI_HAL_GPIOD_02,   CVI_HAL_GPIOD_03,   CVI_HAL_GPIOD_04,   CVI_HAL_GPIOD_05,
	CVI_HAL_GPIOD_06,   CVI_HAL_GPIOD_07,   CVI_HAL_GPIOD_08,   CVI_HAL_GPIOD_09,   CVI_HAL_GPIOD_10,

	CVI_HAL_GPIO_NUM_MIN = CVI_HAL_GPIOD_00,
	CVI_HAL_GPIO_NUM_MAX = CVI_HAL_GPIOA_31
} CVI_HAL_GPIO_NUM_E;

typedef enum _CVI_HAL_GPIO_EDGE_E {
	CVI_HAL_GPIO_EDGE_NONE,   //非中断引脚
	CVI_HAL_GPIO_EDGE_RISING,    //上升沿触发
	CVI_HAL_GPIO_EDGE_FALLING,   //下降沿触发
	CVI_HAL_GPIO_EDGE_BOTH       //边沿触发
} CVI_HAL_GPIO_EDGE_E;

typedef enum _CVI_HAL_GPIO_VALUE_E {
	CVI_HAL_GPIO_VALUE_L,       //低电平
	CVI_HAL_GPIO_VALUE_H        //高电平
} CVI_HAL_GPIO_VALUE_E;


int CVI_GPIO_Export(CVI_HAL_GPIO_NUM_E gpio);
int CVI_HAL_GpioUnexport(CVI_HAL_GPIO_NUM_E gpio);
int CVI_HAL_GpioDirectionInput(CVI_HAL_GPIO_NUM_E gpio);
int CVI_HAL_GpioDirectionOutput(CVI_HAL_GPIO_NUM_E gpio);
int CVI_HAL_GpioSetValue(CVI_HAL_GPIO_NUM_E gpio, CVI_HAL_GPIO_VALUE_E value);
int CVI_HAL_GpioGetValue(CVI_HAL_GPIO_NUM_E gpio, CVI_HAL_GPIO_VALUE_E *value);
int CVI_HAL_GpioPoll(CVI_HAL_GPIO_NUM_E gpio, CVI_HAL_GPIO_EDGE_E edge, FunType Fp);
#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* __GPIO_H__ */
