-include $(TOP_DIR)/.config

.PHONY: all clean install 

all:
	@echo "customer=$(CUSTOMER)"

clean:
	@echo "customer=$(CUSTOMER)"

install:
	cp -rpf $(CUSTOMER)/Others/* $(TOP_DIR)/customer/$(CUSTOMER)/install