# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Cvitek MMC/SD host controller drivers
#

obj-$(CONFIG_MMC_SDHCI_CVI)		+= sdhci-cvi.o
sdhci-cvi-$(CONFIG_ARCH_CV183X)		+= sdhci-cv183x.o
sdhci-cvi-$(CONFIG_ARCH_CV182X)		+= sdhci-cv182x.o
sdhci-cvi-$(CONFIG_ARCH_MARS)		+= sdhci-mars.o
sdhci-cvi-$(CONFIG_ARCH_PHOBOS)		+= sdhci-phobos.o
