obj-$(CONFIG_ARCH_CV183X)	+= clk-cv1835.o
obj-$(CONFIG_ARCH_CV952X)	+= clk-cv1835.o
obj-$(CONFIG_ARCH_CV182X)	+= clk-cv182x.o
obj-$(CONFIG_ARCH_MARS)		+= clk-mars.o
obj-$(CONFIG_ARCH_PHOBOS)		+= clk-phobos.o
