#ifndef MENU_PROFILE_NOTIFICATION_H
#define MENU_PROFILE_NOTIFICATION_H

typedef enum {
    VOICE_NOTICE_MODE_NONE,
    VOICE_NOTICE_MODE_MUSIC,
    VOICE_NOTICE_MODE_END
} VOICE_NOTICE_MODE_E;

typedef enum {
    NAME_DISPLAY_MODE_FULL,
    NAME_DISPLAY_MODE_NAME,
    NAME_DISPLAY_MODE_END
} NAME_DISPLAY_MODE_E;

menu_page_t get_menu_notification_page();

#endif